#!/usr/bin/env python3
"""Generate programs/primes/02-bands.cfg -- Eratosthenes with no divisor baked in.

Every rule here is divisor-agnostic.  What a divisor IS lives on the screen as
matter: a band of p+1 rows between two mirror lines, holding one token that
falls, reflects, rises, reflects.  A token in a band of separation p+1 lands on
a mirror exactly every p columns, because each reflection costs one column:

    =====  mirror              hits alternate floor/ceiling,
     \\   /                     p columns apart
      \\ /
    ==-V-==  mirror

So the band HEIGHT is the divisor.  Nothing in the rule set knows which
divisors exist -- add rows to the terminal and the sieve reaches further.

Machine
-------
  H K   scan head descending the current column (K = a hit was seen)
  D F   the same, one step into "drop a falling token here"
  v ^   token, falling / rising
  =     mirror line          :  left margin        |  right edge
  #  .  prime / composite on the number line (row 1)
  P Q   allocation probe: find the topmost mirror, then return to row 1
  R     45-degree ray: turns a horizontal distance into a vertical one
  L     draws the new mirror line rightwards

One column per number
---------------------
The head walks the current column top to bottom, deriving each cell from the
cell to its LEFT (and that cell's two vertical neighbours) -- a 1-D cellular
automaton whose cells are the rows and whose time axis is the column.  Every
reflection it performs flips it to K.  Wrapping past the last row brings it to
row 1, where K writes '.' and H writes '#' and the scan advances.

Allocation, the only interesting part
-------------------------------------
A new prime p is discovered at column p -- and the distance from the left
margin to that column IS p.  So: probe P walks down column p to the topmost
mirror (row m), drops the band's token just above it, and fires ray R up-left
at 45 degrees.  The ray converts that horizontal p into a vertical p and lands
on the margin at row m-1-p; L then draws the mirror from there.  Separation
m - (m-1-p) = p+1, which is a band of period p.  No counting, no arithmetic,
and nothing in the rules that mentions p.

The token is dropped just above the OLD top mirror in the "just reflected"
state, so its next hit is p columns later, at 2p.

Capacity: bands cost sum(p+1) rows and grow upward.  When a band no longer
fits, the ray dies on the number line and the token it left behind rises until
row 1 absorbs it -- no band, no hits, no corruption; the sieve simply stops
gaining divisors, and stays exact while the smallest missing prime factor
cannot occur.
"""

import os

MARGIN = ':'
WALL = '|'
MIRROR = '='
FALL = 'v'
RISE = '^'
PRIME = '#'
COMP = '.'


def header(sound='=', lhs='H', trig='T', rep=' ', fore='7', back='8',
           ctx=' ', ctxrep=' ', tail=None):
    """Positional header; the field block is emitted in full whenever a
    score/weight tail follows it (GRAMMAR-pitfalls #20, #24)."""
    h = '=' + sound + lhs + trig + rep + fore + back + ctx + ctxrep
    return h + ' ' + tail if tail is not None else h.rstrip()


def body(lhs_cells, rhs_cells):
    """Horizontal body from two (row, col) -> char maps, offsets relative to
    the anchor.  (0,0) is the anchor on the left and the rep cell on the
    right, so neither map mentions it."""
    lhs_cells, rhs_cells = dict(lhs_cells), dict(rhs_cells)
    assert (0, 0) not in lhs_cells and (0, 0) not in rhs_cells

    rows = [r for r, _ in lhs_cells] + [r for r, _ in rhs_cells] + [0]
    lcols = [c for _, c in lhs_cells] + [0]
    rcols = [c for _, c in rhs_cells] + [0]
    r0, r1 = min(rows), max(rows)
    a = -min(lcols)
    b = a + max(lcols) + 1
    q = b + 1 - min(rcols)
    width = q + max(rcols) + 1

    grid = [[' '] * width for _ in range(r1 - r0 + 1)]
    for (r, c), ch in lhs_cells.items():
        grid[r - r0][a + c] = ch
    for (r, c), ch in rhs_cells.items():
        grid[r - r0][q + c] = ch
    grid[-r0][a] = grid[-r0][b] = grid[-r0][q] = '@'
    # Leading space: a body line opening with '#', '^' or '=' is silently
    # reclassified.  Shifting every line keeps all anchor-relative offsets.
    return '\n'.join((' ' + ''.join(row)).rstrip() for row in grid)


out = []
add = out.append


def rule(lhs_cells, rhs_cells, **kw):
    add(header(**kw))
    add(body(lhs_cells, rhs_cells))
    add('')


add('# Sieve of Eratosthenes with no divisor in the rule set.')
add('# Generated by tools/gen_primes2.py -- edit there.')
add('#')
add('# A divisor is a band of rows between two mirror lines, with one token')
add('# bouncing inside it.  Separation p+1 makes the token land on a mirror')
add('# every p columns, so the band HEIGHT is the divisor -- matter, not rule')
add('# geometry.  Enlarge the terminal and the sieve gains divisors by itself.')
add('#')
add('#   H K  scan head (K = hit seen)     v ^  token, falling / rising')
add('#   D F  head about to drop a token   =    mirror        :  left margin')
add('#   P Q  allocation probe             #    prime         .  composite')
add('#   R    45-degree measuring ray      L    mirror-line drawer')
add('#')
add('# Column c is derived from column c-1 alone: the head is a 1-D cellular')
add('# automaton over the rows, stepped once per number.')
add('#help Bands: a divisor is a band of rows, unary   space=pause  c=restart  q=quit')
add('#timing T 3')
add('#transient Q')
add('#control Z pause')
add('#control C clear')
add('#control Q return')
add('#color G 2,BOLD')
add('#color M 4,BOLD')
add('')
add('# --- seeds (must precede every rule: GRAMMAR-pitfalls #19) ---')
add('^')
add('^' + MIRROR + 'l*')       # the first mirror: bottom row, full width
add('^' + MARGIN + '*l')       # left margin, full height
add('^' + WALL + '*r')         # right edge, full height
add('^Sul')                    # setup symbol at (1, 0)
add('')

add('# --- setup: seed column 1 and launch the first head at column 2 ---')
rule({}, {(0, 1): COMP, (1, 2): 'H'}, lhs='S', rep=COMP, fore='4')

# ---------------------------------------------------------------------------
# The scan head.  Reads (0,-1) and its vertical neighbours; writes the derived
# cell at the anchor and hands itself down one row.  Every case is a positive
# literal, so exactly one rule is ever applicable -- the derivation is
# deterministic even though the engine samples at random.
# ---------------------------------------------------------------------------
for s, drop in (('H', 'D'), ('K', 'F')):
    add('# --- scan head %s ---' % s)

    # terrain: copy it one column right.  A cell still occupied by the
    # line-drawer is a mirror in the making -- read it as one, otherwise the
    # head and the drawer wait on each other forever.
    rule({(0, -1): MIRROR}, {(1, 0): s}, lhs=s, rep=MIRROR, fore='M')
    rule({(0, -1): 'L'}, {(1, 0): s}, lhs=s, rep=MIRROR, fore='M')
    rule({(0, -1): '~'}, {(1, 0): s}, lhs=s, rep='~')

    # falling token: reflect off the mirror below, else fall one row
    rule({(0, -1): FALL, (1, -1): MIRROR}, {(1, 0): 'K'},
         lhs=s, rep=RISE, fore='G')
    rule({(0, -1): FALL, (1, -1): '~'}, {(1, 0): drop}, lhs=s, rep='~')

    # rising token: reflect off the mirror above, else rise one row.  Rising
    # writes behind the head, into the cell it has already decided.
    rule({(0, -1): RISE, (-1, -1): MIRROR}, {(1, 0): 'K'},
         lhs=s, rep=FALL, fore='G')
    rule({(0, -1): RISE, (-1, -1): '~'}, {(-1, 0): RISE, (1, 0): s},
         lhs=s, rep='~')
    # a token at row 2 belongs to a band that was never built: absorb it
    rule({(0, -1): RISE, (-1, -1): '%'}, {(1, 0): s},
         lhs=s, rep='~', ctx=PRIME, ctxrep=COMP)

# the drop step: the cell below was empty, so the token lands here
rule({}, {(1, 0): 'H'}, lhs='D', rep=FALL, fore='6')
rule({}, {(1, 0): 'K'}, lhs='F', rep=FALL, fore='6')

# ---------------------------------------------------------------------------
# Verdict.  The head wraps past the last row into row 1, where the cell to its
# left is the previous verdict -- that is how it knows it has come round.
# ---------------------------------------------------------------------------
add('# --- verdict at row 1 (the head has wrapped) ---')
add('# composite: advance. The (0,1) guard halts the scan at the right edge.')
rule({(0, -1): '%', (0, 1): '~'}, {(1, 1): 'H'},
     lhs='K', rep=COMP, fore='4', ctx=PRIME, ctxrep=COMP)

add('# prime: advance, and allocate a band iff row 2 of this column is free')
rule({(0, -1): '%', (0, 1): '~', (1, 0): '~'}, {(1, 0): 'P'},
     lhs='H', rep=PRIME, fore='G', ctx=PRIME, ctxrep=COMP, tail='1 1')
for blocked in (MIRROR, FALL, RISE):
    rule({(0, -1): '%', (0, 1): '~', (1, 0): blocked}, {(1, 1): 'H'},
         lhs='H', rep=PRIME, fore='G', ctx=PRIME, ctxrep=COMP, tail='1 1')

# ---------------------------------------------------------------------------
# Allocation.  P walks down to the topmost mirror; the token goes just above
# it and the ray leaves from just above that.
# ---------------------------------------------------------------------------
add('# --- probe: walk down this column to the topmost mirror ---')
add('# It may meet a rising orphan (a prime whose band did not fit); walking')
add('# over one is harmless -- it belongs to no band and marks nothing.')
rule({(1, 0): '~'}, {(1, 0): 'P'}, lhs='P', rep='~')
for orphan in (FALL, RISE):
    rule({(1, 0): orphan}, {(1, 0): 'P'}, lhs='P', rep='~')
rule({(1, 0): MIRROR, (-1, 0): '~'},
     {(-1, -1): 'R', (1, 0): 'Q'}, lhs='P', rep=RISE, fore='6')
add('# no room above for the ray: skip the allocation, just return')
rule({(1, 0): MIRROR, (-1, 0): '%'}, {(1, 0): 'Q'},
     lhs='P', rep='~', ctx=PRIME, ctxrep=COMP)

add('# --- return: fall through the bands (restoring them) and wrap to row 1,')
add('# which is what releases the next scan head. Serialised on purpose:')
add('# the token must be in place before the next column is derived.')
for below in ('~', MIRROR, FALL, RISE):
    rule({(1, 0): below}, {(1, 0): 'Q'}, lhs='Q', rep='$')
rule({(1, 0): '%', (1, 1): '~'}, {(2, 1): 'H'},
     lhs='Q', rep='$', ctx=PRIME, ctxrep=COMP)

add('# --- the measuring ray: up-left at 45 degrees to the margin ---')
add('# It entered at column c, so it lands exactly c rows higher.')
rule({(-1, -1): '~'}, {(-1, -1): 'R'}, lhs='R', rep='~')
for orphan in (FALL, RISE):
    rule({(-1, -1): orphan}, {(-1, -1): 'R'}, lhs='R', rep='~')
rule({(-1, -1): MARGIN}, {(-1, -1): 'L'}, lhs='R', rep='~')
add('# ray ran into the number line: the field is full, no band is built')
rule({(-1, -1): '%'}, {}, lhs='R', rep='~', ctx=PRIME, ctxrep=COMP)

add('# --- draw the new mirror rightwards to the edge ---')
rule({(0, 1): '~'}, {(0, 1): 'L'}, lhs='L', rep=MIRROR, fore='M')
rule({(0, 1): MIRROR}, {(0, 1): 'L'}, lhs='L', rep=MIRROR, fore='M')
for orphan in (FALL, RISE):
    rule({(0, 1): orphan}, {(0, 1): 'L'}, lhs='L', rep=MIRROR, fore='M')
rule({(0, 1): WALL}, {}, lhs='L', rep=MIRROR, fore='M')

add('# --- controls (engine actions need a rule to fire them: #17) ---')
add('# A head is only ever in ONE of its many states, so anchoring a control')
add('# solely on head glyphs makes the key work only sometimes. Anchor it on')
add('# the seeded scenery too -- that is always on screen.')
for act, key in (('Z', '~'), ('C', 'c'), ('Q', 'q')):
    for cur in ('H', 'K', MARGIN):
        add(header(sound=act, lhs=cur, trig=key))
add(' @@@')
add('')

path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    '..', 'programs', 'primes', '02-bands.cfg')
with open(path, 'w') as fh:
    fh.write('\n'.join(out))
print('wrote %s (%d lines, %d rules)'
      % (os.path.normpath(path), len(out),
         sum(1 for l in out if l.startswith('='))))
