#!/usr/bin/env python3
"""Generate programs/primes/03-counters.cfg -- the sieve with positional counters.

primes  : divisors hardcoded, magnitude = column.
primes2 : divisor = the height of a band, unary, sum(p+1) rows.
primes3 : divisor = a numeral, positional, ONE row per divisor.

Each divisor owns a row holding a record that rides along just left of the
scan column:

    [ dd - kk          d = the divisor, k = columns until its next multiple

Per number every record shifts one column right and k decrements; k = 0 says
the number is a multiple, and the row reloads k from d.  The scan wraps around
the screen, so the number is no longer tied to a column -- it lives in the
odometer row, which is the same machinery counting up instead of down.

Nothing here mentions a divisor either.  What IS in the rules is a digit
table: successor, predecessor and borrow for BASE digits.  That is the price
of positional notation over primes2's pure geometry -- the rule count is
~(8 + 2*NDIG)*BASE, so base 2 is the honest minimum and base 64 is 700+ rules
for one extra digit of range.

Rows
----
  1        verdict marks, rolling
  2        odometer:  " nn          n in base BASE, +1 per column
  3...     divisor records, newest at row 3
  last     floor (stops the allocator from wrapping)

Machine
-------
  > <   scan head walking down the column (< = a multiple was seen)
  } {   odometer increment head: carry / plain copy
  ) (   record copy head: no hit / hit
  ? ,   reload head: borrow / plain copy   (writes k := d-1)
  ; :   allocator: find the last record / push records down one row
  / \\   build the new record: counter half / divisor half
  |     return to the odometer row when there was no room
  " [   record sentinels        -  divisor|counter separator     _  floor

Allocation
----------
A new prime is the current odometer value, and the odometer sits one row above
the newest record -- so allocation pushes every record down one row and then
copies the odometer into the vacated row 3, twice: once as the counter, once
as the divisor.  The two halves are a fixed offset apart, so the same head
does both by changing which cell it reads.

Range: divisors < BASE**NDIG, numbers < BASE**NDIG (the odometer silently
wraps past that).  Exact while the smallest missing prime factor cannot occur.
"""

import os
import sys

# python3 tools/gen_primes3.py [BASE [NDIG]]
BASE = int(sys.argv[1]) if len(sys.argv) > 1 else 10
NDIG = int(sys.argv[2]) if len(sys.argv) > 2 else 3
assert BASE >= 2 and NDIG >= 1

_ALPHABET = ('0123456789abcdefghijklmnopqrstuvwxyz'
             'ABCDEFGHIJKLMNOPQRSTUVWXYZ')
if BASE > len(_ALPHABET):
    _ALPHABET += ''.join(chr(0x100 + i) for i in range(BASE - len(_ALPHABET)))
DIG = _ALPHABET[:BASE]
TOP = DIG[-1]

ODO = '"'          # odometer record sentinel
LBR = '['          # divisor record sentinel
SEP = '-'          # divisor | counter separator
FLOOR = '_'
PRIME, COMP = '#', '.'

# offsets, relative to the scan column, of the record being written
#   K_i at -i, SEP at -NDIG, D_i at -(NDIG+1+i), LBR at -(2*NDIG+1)
BACK = 2 * NDIG + 1        # scan column - LBR column
READ_D = -(NDIG + 2)       # from a new K_i cell to the old D_i cell


def header(sound='=', lhs='>', trig='T', rep=' ', fore='7', back='8',
           ctx=' ', ctxrep=' ', tail=None):
    h = '=' + sound + lhs + trig + rep + fore + back + ctx + ctxrep
    return h + ' ' + tail if tail is not None else h.rstrip()


def body(lhs_cells, rhs_cells):
    """Horizontal body from two (row, col) -> char maps, relative to the
    anchor.  (0,0) is the anchor on the left and the rep cell on the right."""
    lhs_cells, rhs_cells = dict(lhs_cells), dict(rhs_cells)
    assert (0, 0) not in lhs_cells and (0, 0) not in rhs_cells
    rows = [r for r, _ in lhs_cells] + [r for r, _ in rhs_cells] + [0]
    lcols = [c for _, c in lhs_cells] + [0]
    rcols = [c for _, c in rhs_cells] + [0]
    r0, r1 = min(rows), max(rows)
    a = -min(lcols)
    b = a + max(lcols) + 1
    q = b + 1 - min(rcols)
    grid = [[' '] * (q + max(rcols) + 1) for _ in range(r1 - r0 + 1)]
    for (r, c), ch in lhs_cells.items():
        grid[r - r0][a + c] = ch
    for (r, c), ch in rhs_cells.items():
        grid[r - r0][q + c] = ch
    grid[-r0][a] = grid[-r0][b] = grid[-r0][q] = '@'
    return '\n'.join((' ' + ''.join(row)).rstrip() for row in grid)


out = []
add = out.append


def rule(lhs_cells, rhs_cells, **kw):
    add(header(**kw))
    add(body(lhs_cells, rhs_cells))
    add('')


add('# Sieve of Eratosthenes with positional counters: one row per divisor.')
add('# Generated by tools/gen_primes3.py -- edit there (BASE=%d, NDIG=%d).'
    % (BASE, NDIG))
add('#')
add('# Row 2 is an odometer counting up in base %d; every row below it holds' % BASE)
add('#     [ dd - kk      divisor, and columns left until its next multiple')
add('# riding just left of the scan column.  Per number the record shifts one')
add('# column right and kk decrements; kk = 0 means "multiple", and the row')
add('# reloads kk from dd.  The scan wraps, so numbers are not tied to columns.')
add('#')
add('#   > <  scan head (< = multiple seen)   } {  odometer: carry / copy')
add('#   ) (  record shift: clean / hit       ? ,  reload: borrow / copy')
add('#   ; :  allocator: seek / push          / \\  build counter / divisor half')
add('#   |    return with no room             "  [  -  _   sentinels')
add('#')
add('# No rule mentions a divisor. What the rules DO know is the digit table')
add('# for base %d -- that is what positional notation costs over primes2.' % BASE)
add('#help Counters: a divisor is a numeral, records slide   space=pause  c=restart  q=quit')
add('#timing T 0')
add('#transient ;|')
add('#control Z pause')
add('#control C clear')
add('#control Q return')
add('#color G 2,BOLD')
add('#color N 6')
add('#color D 4')
add('')
add('# --- seeds ---')
add('^')
add('^' + FLOOR + 'l*')
add("^'ul")
add('')

# --- setup ---------------------------------------------------------------
add('# --- setup: odometer = 1 at columns 0..%d, scan starts at %d ---'
    % (NDIG, NDIG + 1))
setup = {(0, NDIG): COMP, (1, 0): ODO}
for i in range(NDIG):
    setup[(1, NDIG - i)] = DIG[(1 // BASE ** i) % BASE]
setup[(1, NDIG + 1)] = '}'
rule({}, setup, lhs="'", rep=COMP, fore='D')

# --- odometer ------------------------------------------------------------
add('# --- odometer row: shift one right, add one ---')
for v in range(BASE):
    if v + 1 < BASE:
        rule({(0, -1): DIG[v]}, {(0, -1): '{'}, lhs='}', rep=DIG[v + 1], fore='N')
    else:
        rule({(0, -1): DIG[v]}, {(0, -1): '}'}, lhs='}', rep=DIG[0], fore='N')
for v in range(BASE):
    rule({(0, -1): DIG[v]}, {(0, -1): '{'}, lhs='{', rep=DIG[v], fore='N')
add('# past the most significant digit: hand the column to the scan head')
for head in '}{':
    rule({(0, -1): ODO}, {(0, -1): '~', (1, NDIG): '>'},
         lhs=head, rep=ODO, fore='N')

# --- scan head -----------------------------------------------------------
add('# --- scan head: one row per step, wrapping into row 1 ---')
for s, cp in (('>', ')'), ('<', '(')):
    rule({(0, -1): '~'}, {(1, 0): s}, lhs=s, rep='~')
    rule({(0, -1): FLOOR}, {(1, 0): s}, lhs=s, rep=FLOOR, fore='D')

    add('# a record row: decrement the counter.  One rule per position of the')
    add('# lowest non-zero digit, so the whole borrow chain is a single step.')
    for j in range(NDIG):
        for v in range(1, BASE):
            lhs_cells = {(0, -k - 1): DIG[0] for k in range(j)}
            lhs_cells[(0, -(j + 1))] = DIG[v]
            rhs_cells = {(0, -k): TOP for k in range(1, j)}
            if j:
                rhs_cells[(0, -j)] = DIG[v - 1]
            rhs_cells[(0, -(j + 1))] = cp
            rule(lhs_cells, rhs_cells,
                 lhs=s, rep=(TOP if j else DIG[v - 1]), fore='N')
    add('# counter already 0: this number is a multiple -- reload from dd')
    rule({(0, -k - 1): DIG[0] for k in range(NDIG)}, {}, lhs=s, rep='?')

add('# --- verdict (the head has wrapped into row 1) ---')
rule({(0, -1): '%'}, {(1, 1): '}'}, lhs='<', rep=COMP, fore='D',
     ctx=PRIME, ctxrep=COMP)
add('# prime: allocate a row for it, starting from the newest record')
rule({(0, -1): '%'}, {(2, 0): ';'}, lhs='>', rep=PRIME, fore='G',
     ctx=PRIME, ctxrep=COMP, tail='1 1')

# --- record shift --------------------------------------------------------
add('# --- record shift: copy the rest of the record one column right ---')
for cp, s in ((')', '>'), ('(', '<')):
    for v in range(BASE):
        rule({(0, -1): DIG[v]}, {(0, -1): cp}, lhs=cp, rep=DIG[v], fore='N')
    rule({(0, -1): SEP}, {(0, -1): cp}, lhs=cp, rep=SEP, fore='D')
    rule({(0, -1): LBR}, {(0, -1): '~', (1, BACK): s}, lhs=cp, rep=LBR, fore='D')

# --- reload --------------------------------------------------------------
add('# --- reload: kk := dd - 1, read from a fixed offset, borrow first ---')
for v in range(BASE):
    if v > 0:
        rule({(0, READ_D): DIG[v]}, {(0, -1): ','}, lhs='?', rep=DIG[v - 1],
             fore='G')
    else:
        rule({(0, READ_D): DIG[v]}, {(0, -1): '?'}, lhs='?', rep=TOP, fore='G')
for v in range(BASE):
    rule({(0, READ_D): DIG[v], (0, -1): '!'}, {(0, -1): ','},
         lhs=',', rep=DIG[v], fore='G', ctx=SEP)
rule({(0, -1): SEP}, {(0, -1): '('}, lhs=',', rep=SEP, fore='D')

# --- allocation ----------------------------------------------------------
add('# --- allocate: walk to the last record, then push every record down ---')
add('# a record lives in this row -> keep going down')
rule({(0, -BACK): LBR}, {(1, 0): ';'}, lhs=';', rep='$')
add('# this row is free: push the records into it, or build here if there')
add('# are none yet (the row above is then the odometer, not a record)')
rule({(0, -BACK): '~', (-1, -BACK): LBR}, {}, lhs=';', rep=':')
rule({(0, -BACK): '~', (-1, -BACK): '!'}, {}, lhs=';', rep='/', ctx=LBR)
add('# the floor: no room for another divisor, return empty-handed')
rule({(0, -BACK): FLOOR}, {(-1, 0): '|'}, lhs=';', rep='$')

rule({(-1, -NDIG): ODO}, {(-1, 1): '}'}, lhs='|', rep='$')
rule({(-1, -NDIG): '!'}, {(-1, 0): '|'}, lhs='|', rep='$', ctx=ODO)

add('# push one record down a row, then step up to the next one')
for v in range(BASE):
    rule({(-1, 0): DIG[v]}, {(0, -1): ':'}, lhs=':', rep=DIG[v], fore='N')
rule({(-1, 0): SEP}, {(0, -1): ':'}, lhs=':', rep=SEP, fore='D')
add('# reached the sentinel: is the row above the odometer? then build here')
rule({(-1, 0): LBR, (-2, NDIG + 1): ODO}, {(-1, BACK): '/'},
     lhs=':', rep=LBR, fore='D')
rule({(-1, 0): LBR, (-2, NDIG + 1): '!'}, {(-1, BACK): ':'},
     lhs=':', rep=LBR, fore='D', ctx=ODO)

add('# --- build the new record from the odometer directly above ---')
add('# The counter half is n-1, not n: k counts the columns remaining AFTER')
add('# this one, so a divisor found at n next strikes at 2n.  The build head')
add('# walks from the least significant digit, so the borrow runs with it.')
for v in range(BASE):
    if v > 0:
        rule({(-1, 0): DIG[v]}, {(0, -1): '+'}, lhs='/', rep=DIG[v - 1], fore='G')
    else:
        rule({(-1, 0): DIG[v]}, {(0, -1): '/'}, lhs='/', rep=TOP, fore='G')
for v in range(BASE):
    rule({(-1, 0): DIG[v]}, {(0, -1): '+'}, lhs='+', rep=DIG[v], fore='G')
for h in '/+':
    rule({(-1, 0): ODO}, {(0, -1): '\\'}, lhs=h, rep=SEP, fore='D')
for v in range(BASE):
    rule({(-1, NDIG + 1): DIG[v]}, {(0, -1): '\\'}, lhs='\\', rep=DIG[v],
         fore='G')
rule({(-1, NDIG + 1): ODO}, {(-1, BACK + 1): '}'}, lhs='\\', rep=LBR, fore='D')

add('# --- controls (engine actions need a rule to fire them: #17) ---')
for act, key in (('Z', '~'), ('C', 'c'), ('Q', 'q')):
    for cur in ('>', '<'):
        add(header(sound=act, lhs=cur, trig=key))
add(' @@@')
add('')

path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    '..', 'programs', 'primes', '03-counters.cfg')
with open(path, 'w') as fh:
    fh.write('\n'.join(out))
print('wrote %s  base=%d digits=%d  %d rules'
      % (os.path.normpath(path), BASE, NDIG,
         sum(1 for l in out if l.startswith('='))))
